### ISSUE TITLE
CLI download

### ISSUE THREAD

**Issue by AmitMY** [TheLanguageArchive/Arbil#5]
I would like to download datasets ([for example](https://archive.mpi.nl/tla/islandora/object/tla%3A1839_00_0000_0000_0004_DF8E_6)) using the command line.

Does Arbil have any CLI?

**Comment by twagoo** [comment]
Hi! Thanks for your question. Arbil does not have a command line interface. Depending on the exact datasets, it may be possible to download datasets in bulk using a script or even functionality of the repository system. Are you looking to download data from The Language Archive specifically? If so, I believe that this is more of a question related to the archive as a whole. I would suggest [contacting the maintainers of the archive](https://archive.mpi.nl/tla/contact) about this.
